// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-oBcV_aT5jLFWbDBBFvm323H_vLTResA',
    appId: '1:662912945422:web:261260ff023cc06a951b5f',
    messagingSenderId: '662912945422',
    projectId: 'simp-auth-84531',
    authDomain: 'simp-auth-84531.firebaseapp.com',
    storageBucket: 'simp-auth-84531.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGXMvrthM-g1EUgOX_zo0_edYLDn5ORms',
    appId: '1:662912945422:android:53ae770086c22849951b5f',
    messagingSenderId: '662912945422',
    projectId: 'simp-auth-84531',
    storageBucket: 'simp-auth-84531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1jXP7wFvJ0gr-O-3sWdxZseWKv6bnFc',
    appId: '1:662912945422:ios:66fb6b012e2d17ba951b5f',
    messagingSenderId: '662912945422',
    projectId: 'simp-auth-84531',
    storageBucket: 'simp-auth-84531.appspot.com',
    iosClientId: '662912945422-0scve6mj4m3k4f4tlarifdj7r9cgj7n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1jXP7wFvJ0gr-O-3sWdxZseWKv6bnFc',
    appId: '1:662912945422:ios:ea6d503a645b7617951b5f',
    messagingSenderId: '662912945422',
    projectId: 'simp-auth-84531',
    storageBucket: 'simp-auth-84531.appspot.com',
    iosClientId: '662912945422-53tjjtt6m75qjjv7qnrub8tasvmbkdgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
